### ISSUE TITLE
⚙️ Create centralized configuration system for game balance and settings

### ISSUE THREAD

**Issue by chriswingler** [chriswingler/wildfire-cli#105]
## Configuration Management Implementation

**Priority**: High
**Impact**: Game balance, maintainability, deployment flexibility

## Problem

Critical game values are hardcoded throughout the application, making it difficult to:
- Adjust game balance without code changes
- Deploy different configurations for testing/production
- Maintain consistency across different deployment environments

### Resource Costs (discord_wildfire.py:577)
```python
costs = {"hand_crews": 1800, "engines": 3200, "dozers": 4600, "air_tankers": 12000}
```

### Budget Values
- Starting budget: 20,000 (lines 243, 531, 553)
- Bonus amount: 8,000 
- Critical failure threshold: 200 acres (lines 669, 997)

### Timeouts and Thresholds  
- Button timeout: 300 seconds (lines 24, 176)
- Fire size ranges: 30-100 acres (line 740)
- Auto-progression intervals

### Effectiveness Multipliers (lines 472-476)
- Terrain effectiveness values
- Weather impact factors
- Resource type modifiers

### 1. Create Configuration Structure
```yaml
# config/game_balance.yaml
game:
  economy:
    starting_budget: 20000
    bonus_amount: 8000
    resource_costs:
      hand_crews: 1800
      engines: 3200
      dozers: 4600
      air_tankers: 12000
  
  thresholds:
    critical_failure_acres: 200
    fire_size_range: [30, 100]
    button_timeout_seconds: 300
  
  effectiveness:
    terrain_multipliers:
      flat: 1.0
      hilly: 0.8  
      mountainous: 0.6
    weather_impact:
      normal: 1.0
      high_wind: 0.7
      extreme_dry: 0.5
```

### 2. Configuration Loader Class
```python
# src/config/settings.py
import yaml
from dataclasses import dataclass
from typing import Dict, List

@dataclass  
class GameConfig:
    starting_budget: int
    bonus_amount: int
    resource_costs: Dict[str, int]
    critical_failure_acres: int
    # ... other settings

class ConfigManager:
    def load_config(self, env: str = "production") -> GameConfig:
        # Load environment-specific configuration
```

### 3. Environment-Specific Configs
- `config/development.yaml` - Lower costs, faster progression for testing
- `config/testing.yaml` - Predictable values for unit tests  
- `config/production.yaml` - Balanced values for live gameplay

### Phase 1: Core Infrastructure
- [ ] Create configuration directory structure
- [ ] Implement ConfigManager class
- [ ] Add YAML dependency to requirements.txt
- [ ] Create base configuration templates

### Phase 2: Migration  
- [ ] Replace hardcoded resource costs
- [ ] Replace hardcoded budget values
- [ ] Replace hardcoded thresholds and timeouts
- [ ] Replace effectiveness multipliers

### Phase 3: Environment Support
- [ ] Add environment detection (ENV var)
- [ ] Create environment-specific config files
- [ ] Update deployment documentation

### Phase 4: Validation
- [ ] Add configuration validation
- [ ] Create configuration schema
- [ ] Add helpful error messages for invalid configs

## Benefits

- **Game Balance**: Easy tuning without code deployment
- **Testing**: Predictable test configurations  
- **Deployment**: Environment-specific settings
- **Maintainability**: Centralized value management
- **Documentation**: Clear configuration reference

## Definition of Done

- [ ] All hardcoded game values moved to configuration files
- [ ] ConfigManager class implemented and tested
- [ ] Environment-specific configurations created
- [ ] Configuration validation implemented
- [ ] Documentation updated with configuration reference
- [ ] No functional changes to default game behavior

**Automation Suitability**: Excellent for Jules - systematic refactoring with clear patterns
